# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-10 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_firestore', '0004_auto_20220110_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='firestoreID',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
